endpoints:
  - url: 'https://example.com/api'
    verbose: false
    method: 'GET'
    headers: 
      Authorization: 'Bearer your_token'
      Content-Type: 'application/json'
    count: 10
    concurrency: 20
  - url: 'https://example.com/v2/api'
    verbose: false
    method: 'POST'
    headers: 
      Authorization: 'Bearer your_token'
      Content-Type: 'application/json'
      Key: 'Value'
    data:
      foo: 'bar'
    count: 10
    concurrency: 20